# Generated by Django 4.1.5 on 2023-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0009_alter_comment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка игры'),
        ),
    ]
