# Generated by Django 4.1.5 on 2023-01-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0003_category_games_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='games_amount',
            field=models.IntegerField(default=0, verbose_name='Колличество игр в категории'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='game_store_category_name_index'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='game_store_game_name_index'),
        ),
    ]
