# Generated by Django 4.1.5 on 2023-01-27 10:39

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    Category = apps.get_model("game_store", "Category")
    db_alias = schema_editor.connection.alias
    for category in Category.objects.all():
        category.games_amount = category.game_set.count()
        category.save()

def remove_func(apps, schema_editor):
    Category = apps.get_model("game_store", "Category")
    db_alias = schema_editor.connection.alias
    Category.objects.using(db_alias).update(games_amount=None)

class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0002_alter_category_description_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='games_amount',
            field=models.IntegerField(default=0, verbose_name='Колличество игр'),
        ),
        migrations.RunPython(forwards_func, remove_func)
    ]
