# Generated by Django 4.1.5 on 2023-01-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0002_rename_posts_post_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
