# Generated by Django 4.1.5 on 2023-01-10 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.EmailValidator(message='Введите корректный email')]),
        ),
    ]
