# Generated by Django 4.1.5 on 2023-01-10 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0004_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(regex='/^[a-z0-9_-]{3,16}$/')]),
        ),
    ]
