# Generated by Django 4.1.5 on 2023-02-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0014_remove_comment_name_comment_user_alter_comment_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
