# Generated by Django 4.1.5 on 2023-02-03 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0005_remove_category_title_category_name_alter_game_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя комментатора')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('grade', models.CharField(choices=[('D', '1'), ('C', '2'), ('E', '3'), ('B', '4'), ('A', '5')], max_length=1, verbose_name='Оценка игры')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='game_store.game')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
